import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/font.css";
import { Montserrat_Subrayada } from "next/font/google";
import localFont from "next/font/local";
import StoreProvider from "@/global/StoreProvider";

const monteserrat = localFont({
	src: "../fonts/Montserrat-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
	title: "Topper Folio",
	description: "Generated by create next app",

	icons: {
		icon: ["/favicon.ico?v=4"],
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${monteserrat.className} bg-black`}>
				<StoreProvider>{children}</StoreProvider>
			</body>
		</html>
	);
}
